## I'm going to use this notebook for investigating the "macro.csv" file. If I find anything worth while, I'll add it to the main notebook for this project.

In [1]:
## usual data analysis imports
import numpy as np
import pandas as pd

In [11]:
macro = pd.read_csv('macro.csv', parse_dates=True, index_col='timestamp')

In [12]:
macro.head()

,oil_urals,gdp_quart,gdp_quart_growth,cpi,ppi,gdp_deflator,balance_trade,balance_trade_growth,usdrub,eurrub,...,provision_retail_space_modern_sqm,turnover_catering_per_cap,theaters_viewers_per_1000_cap,seats_theather_rfmin_per_100000_cap,museum_visitis_per_100_cap,bandwidth_sports,population_reg_sports_share,students_reg_sports_share,apartment_build,apartment_fund_sqm
timestamp,,,,,,,,,,,,,,,,,,,,,
2010-01-01,76.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,690.0,6221.0,527.0,0.41,993.0,NaN,NaN,63.03,22825.0,NaN
2010-01-02,76.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,690.0,6221.0,527.0,0.41,993.0,NaN,NaN,63.03,22825.0,NaN
2010-01-03,76.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,690.0,6221.0,527.0,0.41,993.0,NaN,NaN,63.03,22825.0,NaN
2010-01-04,76.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.905,43.4054,...,690.0,6221.0,527.0,0.41,993.0,NaN,NaN,63.03,22825.0,NaN
2010-01-05,76.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.836,42.9600,...,690.0,6221.0,527.0,0.41,993.0,NaN,NaN,63.03,22825.0,NaN

In [13]:
macro.columns

Index(['oil_urals', 'gdp_quart', 'gdp_quart_growth', 'cpi', 'ppi',
       'gdp_deflator', 'balance_trade', 'balance_trade_growth', 'usdrub',
       'eurrub', 'brent', 'net_capital_export', 'gdp_annual',
       'gdp_annual_growth', 'average_provision_of_build_contract',
       'average_provision_of_build_contract_moscow', 'rts', 'micex',
       'micex_rgbi_tr', 'micex_cbi_tr', 'deposits_value', 'deposits_growth',
       'deposits_rate', 'mortgage_value', 'mortgage_growth', 'mortgage_rate',
       'grp', 'grp_growth', 'income_per_cap',
       'real_dispos_income_per_cap_growth', 'salary', 'salary_growth',
       'fixed_basket', 'retail_trade_turnover',
       'retail_trade_turnover_per_cap', 'retail_trade_turnover_growth',
       'labor_force', 'unemployment', 'employment',
       'invest_fixed_capital_per_cap', 'invest_fixed_assets',
       'profitable_enterpr_share', 'unprofitable_enterpr_share',
       'share_own_revenues', 'overdue_wages_per_cap', 'fin_res_per_cap',
       'marriages_per_1000_cap', 'divorce_rate', 'construction_value',
       'invest_fixed_assets_phys', 'pop_natural_increase', 'pop_migration',
       'pop_total_inc', 'childbirth', 'mortality', 'housing_fund_sqm',
       'lodging_sqm_per_cap', 'water_pipes_share', 'baths_share',
       'sewerage_share', 'gas_share', 'hot_water_share',
       'electric_stove_share', 'heating_share', 'old_house_share',
       'average_life_exp', 'infant_mortarity_per_1000_cap',
       'perinatal_mort_per_1000_cap', 'incidence_population',
       'rent_price_4+room_bus', 'rent_price_3room_bus', 'rent_price_2room_bus',
       'rent_price_1room_bus', 'rent_price_3room_eco', 'rent_price_2room_eco',
       'rent_price_1room_eco', 'load_of_teachers_preschool_per_teacher',
       'child_on_acc_pre_school', 'load_of_teachers_school_per_teacher',
       'students_state_oneshift', 'modern_education_share',
       'old_education_build_share', 'provision_doctors', 'provision_nurse',
       'load_on_doctors', 'power_clinics', 'hospital_beds_available_per_cap',
       'hospital_bed_occupancy_per_year', 'provision_retail_space_sqm',
       'provision_retail_space_modern_sqm', 'turnover_catering_per_cap',
       'theaters_viewers_per_1000_cap', 'seats_theather_rfmin_per_100000_cap',
       'museum_visitis_per_100_cap', 'bandwidth_sports',
       'population_reg_sports_share', 'students_reg_sports_share',
       'apartment_build', 'apartment_fund_sqm'],
      dtype='object')

In [14]:
macro.shape

(2484, 99)

In [15]:
macro.describe()

,oil_urals,gdp_quart,gdp_quart_growth,cpi,ppi,gdp_deflator,balance_trade,balance_trade_growth,usdrub,eurrub,...,provision_retail_space_modern_sqm,turnover_catering_per_cap,theaters_viewers_per_1000_cap,seats_theather_rfmin_per_100000_cap,museum_visitis_per_100_cap,bandwidth_sports,population_reg_sports_share,students_reg_sports_share,apartment_build,apartment_fund_sqm
count,2484.000000,2394.000000,2394.000000,2453.000000,2453.000000,2119.000000,2453.000000,2394.000000,2481.000000,2481.000000,...,730.000000,2191.000000,1461.00000,2191.000000,1461.000000,1826.000000,1461.00000,1461.000000,1826.000000,1826.000000
mean,86.467157,16993.230075,1.523726,407.808398,480.216347,110.122308,15.344006,16.846742,40.732406,50.444801,...,480.500000,8691.922410,580.51540,0.443398,1245.543463,349902.577766,25.06859,67.800034,36282.434830,230615.059255
std,27.528709,3187.074480,2.875659,65.895969,70.286366,14.818429,3.878104,16.988727,15.006583,13.905912,...,209.643641,1668.967502,37.98811,0.016061,162.526951,72146.453110,2.44944,5.168602,10761.669111,2944.879242
min,29.112500,9995.800000,-4.500000,315.100000,337.200000,86.721000,5.823000,-4.100000,27.276300,37.445400,...,271.000000,6221.000000,527.00000,0.410000,993.000000,269768.000000,22.37000,63.030000,22825.000000,226047.300000
25%,61.283300,14925.000000,0.400000,354.000000,438.400000,100.000000,12.785000,7.200000,30.508800,40.242600,...,271.000000,6943.000000,565.00000,0.439390,1240.000000,288177.000000,23.01000,64.120000,23587.000000,229294.800000
50%,101.416500,17442.100000,1.300000,393.000000,473.500000,108.299000,16.041000,10.500000,32.316500,42.862200,...,480.500000,8522.000000,603.00000,0.450700,1309.000000,329348.000000,23.01000,67.850000,42551.000000,230310.000000
75%,109.310000,19284.100000,4.100000,469.400000,520.700000,123.661000,18.076000,21.500000,53.752300,61.323700,...,690.000000,10311.000000,603.00000,0.453560,1309.000000,398451.000000,26.70000,67.850000,46080.000000,232840.200000
max,122.520000,22016.100000,5.200000,531.000000,606.100000,133.160000,21.939000,75.800000,82.276400,90.881500,...,690.000000,10805.000000,627.00000,0.458880,1440.000000,463938.000000,28.20000,76.200000,46352.000000,234576.900000

In [10]:
macro.dtypes

timestamp                                      object
oil_urals                                     float64
gdp_quart                                     float64
gdp_quart_growth                              float64
cpi                                           float64
ppi                                           float64
gdp_deflator                                  float64
balance_trade                                 float64
balance_trade_growth                          float64
usdrub                                        float64
eurrub                                        float64
brent                                         float64
net_capital_export                            float64
gdp_annual                                    float64
gdp_annual_growth                             float64
average_provision_of_build_contract           float64
average_provision_of_build_contract_moscow    float64
rts                                           float64
micex                                         float64
micex_rgbi_tr                                 float64
micex_cbi_tr                                  float64
deposits_value                                  int64
deposits_growth                               float64
deposits_rate                                 float64
mortgage_value                                  int64
mortgage_growth                               float64
mortgage_rate                                 float64
grp                                           float64
grp_growth                                    float64
income_per_cap                                float64
                                               ...
rent_price_4+room_bus                         float64
rent_price_3room_bus                          float64
rent_price_2room_bus                          float64
rent_price_1room_bus                          float64
rent_price_3room_eco                          float64
rent_price_2room_eco                          float64
rent_price_1room_eco                          float64
load_of_teachers_preschool_per_teacher        float64
child_on_acc_pre_school                        object
load_of_teachers_school_per_teacher           float64
students_state_oneshift                       float64
modern_education_share                         object
old_education_build_share                      object
provision_doctors                             float64
provision_nurse                               float64
load_on_doctors                               float64
power_clinics                                 float64
hospital_beds_available_per_cap               float64
hospital_bed_occupancy_per_year               float64
provision_retail_space_sqm                    float64
provision_retail_space_modern_sqm             float64
turnover_catering_per_cap                     float64
theaters_viewers_per_1000_cap                 float64
seats_theather_rfmin_per_100000_cap           float64
museum_visitis_per_100_cap                    float64
bandwidth_sports                              float64
population_reg_sports_share                   float64
students_reg_sports_share                     float64
apartment_build                               float64
apartment_fund_sqm                            float64
dtype: object